start: rule                                             -> start

rule: "{" binding_list "}" "|=" expr                    -> rule

binding_list: binding ("," binding)*                    -> binding_list
binding: VAR ":" type                                   -> binding

type: "tensor"                                          -> tensor_type
    | "int"                                             -> int_type
    | "float"                                           -> float_type
    | "bool"                                            -> bool_type
    | "dtype"                                           -> dtype_type
    | "str"                                             -> str_type
    | "list" "(" type ")"          			            -> list_type     
    | "tuple" "(" type ")"          			        -> tuple_type
    | "dimension_numbers"                               -> dimension_numbers_type     
    | type "⊎" type                                     -> union_type

?expr: and_expr                                         -> expr

?and_expr: or_expr                                      -> and_expr_base
         | and_expr "∧" or_expr                         -> and_

?or_expr: quant_expr                                    -> or_expr_base
        | or_expr "∨" quant_expr                        -> or_

?quant_expr: "∀" prim_var "∈" "[" expr "," expr "]" ":" expr -> forall
           | "∃" prim_var "∈" "[" expr "," expr "]" ":" expr -> exists
           | if_expr
           | compare_expr

if_expr: "if" expr "then" expr ("else" expr)?           -> if_expr

?compare_expr: arith_expr                               -> compare_expr_base
             | arith_expr COMPOP arith_expr             -> compare

?arith_expr: arith_expr ADDOP arith_term                -> binop
           | arith_term                                 -> arith_expr_base

?arith_term: arith_term MULOP arith_factor              -> binop
           | arith_factor                               -> arith_term_base

?arith_factor: tuple_var tuple_access                   -> tuple_access 
	     | func_call                                -> arith_func_call 
             | constant                                 -> arith_constant
             | prim_var                                 -> arith_var
             | "(" expr ")"                             -> parens

tuple_access: "[" expr "]"       			-> tuple_index
            | ".len"            			-> tuple_len

func_call: FUNC "(" tensor_var ("," expr)? ")"          -> func_call

?constant: SIGNED_NUMBER                                -> number
         | "true"                                       -> true
         | "false"                                      -> false
         | ESCAPED_STRING                               -> string

COMPOP: "<=" | ">=" | "!=" | "=" | "≠" | ">" | "<" | "≥" | "≤"
ADDOP: "+" | "-"
MULOP: "*" | "/" | "×" | "%"

FUNC.2: "ndim" | "shape" | "dtype_" | "min" | "max"

VAR: /[a-zA-Z_][a-zA-Z_0-9]*/

prim_var: VAR                                           -> prim_var
tensor_var: VAR                                         -> tensor_var
tuple_var: VAR                                          -> tuple_var

%import common.SIGNED_NUMBER
%import common.ESCAPED_STRING
%import common.WS
%ignore WS
